require("dotenv").config();
const globalConfig = require("../globalConfig.json");

const PORT = process.env.PORT || 3001;

const ENV = process.env.NODE_ENV || "development";
const IN_PROD = ENV === "production";

const POSTGRES_USER_DEV = process.env.POSTGRES_USER_DEV;
const POSTGRES_HOST_DEV = process.env.POSTGRES_HOST_DEV;
const POSTGRES_DATABASE_DEV = process.env.POSTGRES_DATABASE_DEV;
const POSTGRES_PASSWORD_DEV = process.env.POSTGRES_PASSWORD_DEV;

const POSTGRES_USER_PROD = process.env.POSTGRES_USER_PROD;
const POSTGRES_HOST_PROD = process.env.POSTGRES_HOST_PROD;
const POSTGRES_DATABASE_PROD = process.env.POSTGRES_DATABASE_PROD;
const POSTGRES_PASSWORD_PROD = process.env.POSTGRES_PASSWORD_PROD;

const SESSION_NAME = globalConfig.SESSION_NAME;
const SESSION_SECRET = process.env.SESSION_SECRET;
const SESSION_COOKIE_MAX_AGE = 1000 * 60 * 60 * 2;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

module.exports = {
  PORT,
  IN_PROD,
  ENV,
  POSTGRES_USER_DEV,
  POSTGRES_HOST_DEV,
  POSTGRES_DATABASE_DEV,
  POSTGRES_PASSWORD_DEV,
  POSTGRES_USER_PROD,
  POSTGRES_HOST_PROD,
  POSTGRES_DATABASE_PROD,
  POSTGRES_PASSWORD_PROD,
  SESSION_NAME,
  SESSION_SECRET,
  SESSION_COOKIE_MAX_AGE,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
};
